# avid-task3/.github/workflows/use_generate_task.yml

name: Use Generate Task Workflow

on:
  workflow_dispatch:
    inputs:
      theme:
        description: 'Theme for the new task'
        required: true
        type: string
        default: 'Sample theme'
      difficulty:
        description: 'Difficulty level for the new task'
        required: true
        type: string
        default: 'medium'
        # Expected values: basic, medium, hard
      language:
        description: 'Natural language for the task description'
        required: true
        type: string
        default: 'English'

jobs:
  call-generate-task:
    name: Call Generate Task Reusable Workflow
    uses: alinda-24/task3/.github/workflows/generate_task.yml@v1.0.1  # Updated tag pointing to minimal workflow
    with:
      theme: ${{ inputs.theme }}
      difficulty: ${{ inputs.difficulty }}
      language: ${{ inputs.language }}
    secrets:
      OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
      # Removed GITHUB_TOKEN to avoid collision with reserved name
